services:
  zrok:
    image: kbinghamnetfoundry/zrok:main
    volumes:
      - ~/.zrok:/root/.zrok
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - ZROK_TOKEN=${ZROK_TOKEN}
    entrypoint: /entrypoint.sh
    networks:
      - n8n-ngrok_n8n-network
    stdin_open: true  # Keep STDIN open
    tty: true         # Allocate a pseudo-TTY
    restart: unless-stopped  # Ensure the container restarts automatically

networks:
  n8n-ngrok_n8n-network:
    external: true